#!/bin/bash

function __cpp__ {
  if [[ "$OSTYPE" == "linux-gnu"* ]];
    then
      echo "use gcc or g++ or what is called here for linux, same params I think"
  elif [[ "$OSTYPE" == "darwin"* ]];
    then
      echo CMD: clang++ -std=c++17 -pedantic-errors -Wall -Weffc++ -Wextra -Wsign-conversion $1.cpp -o $1.out
      clang++ -std=c++17 -pedantic-errors -Wall -Weffc++ -Wextra -Wsign-conversion $1.cpp -o $1.out
  fi
    if [[ $2 = "e" ]];
    then
        echo CMD: ./$1.out
        echo
        ./$1.out
    fi
}

function __java__ {
    if [[ $2 = "e" ]];
    then
        echo "CMD: javac $1.java && java $1"
        echo
        javac $1.java && java $1
    else
        echo CMD: "javac $1.java"
        echo
        javac $1.java
    fi
}

function __START__ {
    if [[ $1 = 'cpp' ]];
    then
        __cpp__ $2 $3;
    elif [[ $1 = 'java' ]];
    then
        __java__ $2 $3;
    else
        echo fyi, ca stands for "compiler aliases"
        echo ex: ca cpp [filename/path] e // adding e will run the compiled file
        echo functions available: cpp, java .. more to come ..
        echo
    fi
}

__START__ $1 $2 $3
